#include "../inc/minishell.h"
#include <stdio.h>
#include <stdlib.h>

char *copy_string (char *str) {
    int len = 0;
    while (str[len] != '\0') {
        len++;
    }

    char *new_str = (char*)malloc(sizeof(char) * (len + 1));
    if (!new_str) {
        printf("Error creating *new_str.\n");
        return NULL;
    }

    int i = 0;
    while (i < len) {
        new_str[i] = str[i];
        i++;
    }
    new_str[i] = '\0';

    return new_str;
}

t_ast_node *create_node (t_node_type type) {
    t_ast_node *node = calloc(1, sizeof(t_ast_node));
    if (!node) {
        printf("Error creating a node\n");
        return NULL;
    }

    node->type = type;

    return node;
}

void add_argument (t_ast_node *node, char *new_arg) {
    int i = 0;

    if (node->args != NULL) {
        while (node->args[i] != NULL) {
            i++;
        }
    }

    char **new_args = (char**)malloc(sizeof(char*) * (i + 2));
    if (!new_args) {
        printf("Error creating **new_args.");
        return;
    }

    int j = 0;
    while (j < i) {
        new_args[j] = node->args[j];
        j++;
    }

    new_args[j] = copy_string(new_arg);
    new_args[j+1] = NULL;

    free(node->args);

    node->args = new_args;
}

int is_redir_token (t_token_type type) {
    return (type == TOKEN_REDIR_IN || type == TOKEN_REDIR_OUT || type == TOKEN_APPEND || type == TOKEN_HEREDOC);
}

// TODO: free_ast to free the whole tree
void free_ast (t_ast_node *node) {
    if (node == NULL) return;

    free_ast(node->left);
    free_ast(node->right);

    if (node->type == NODE_CMD && node->args != NULL) {
        int i = 0;
        while (node->args[i] != NULL) {
            free(node->args[i]);
            i++;
        }
        free(node->args);
    }
    else if (node->type == NODE_REDIR && node->value != NULL) {
        free(node->value);
    }

    free(node);
}


// TODO: free_tokens to free the token list
void free_tokens (t_token *head) {
    if (head == NULL) return;

    t_token *next = head;
    while (next != NULL) {
        next = next->next;
        if (head->value) {
            free(head->value);
        }
        free(head);
        head = next;
    }
}

t_ast_node *parse_cmd (t_token **curr) {
    t_ast_node *cmd_node = create_node(NODE_CMD);

    while ((*curr) != NULL && (*curr)->type == TOKEN_WORD) {
        add_argument(cmd_node, (*curr)->value);
        *curr = (*curr)->next;
    }

    return cmd_node;
}

t_ast_node *parse_redir (t_token **curr) {
    t_ast_node *node = parse_cmd(curr);

    while ((*curr) != NULL && is_redir_token((*curr)->type)) {
        t_token_type redir_type = (*curr)->type;
        *curr = (*curr)->next;

        if (*curr == NULL || (*curr)->type != TOKEN_WORD) {
            printf("Syntax error: file name is missing or consecutive redirection\n");
            free_ast(node);
            return NULL;
        }

        char *file_val = copy_string((*curr)->value);
        *curr = (*curr)->next;

        t_ast_node *redir_node = calloc(1, sizeof(t_ast_node));
        if (!redir_node) {
            free_ast(node);
            return NULL;
        }

        redir_node->type = NODE_REDIR;
        redir_node->redir_type = redir_type;
        redir_node->value = file_val;
        
        redir_node->left = node;
        node = redir_node;
    }

    return node;
}

t_ast_node *parse_pipe (t_token **curr) {
    t_ast_node *node = parse_redir(curr);

    while ((*curr) != NULL && (*curr)->type == TOKEN_PIPE) {
        *curr = (*curr)->next;

        if (*curr == NULL || (*curr)->type == TOKEN_PIPE) {
            printf("Syntax error: invalid pipe or consecutive pipe sign\n");
            free_ast(node);
            return NULL;
        }

        t_ast_node *right = parse_redir(curr);

        t_ast_node *pipe_node = calloc(1, sizeof(t_ast_node));
        if (!pipe_node) {
            free_ast(node);
            free_ast(right);
            return NULL;
        }

        pipe_node->type = NODE_PIPE;
        pipe_node->left = node;
        pipe_node->right = right;
        node = pipe_node;
    }
    return node;
}

// takes token list and generate ast
t_ast_node *generate_ast (t_token *head) {
    t_token *curr = head;
    t_ast_node *root = parse_pipe(&curr);

    free_tokens(head);

    return root;
}

// Test parser generated by Gemini
void print_ast(t_ast_node *node, int depth) {
    if (node == NULL) return;

    // 뎁스(Depth)만큼 들여쓰기해서 트리 모양 내기
    for (int i = 0; i < depth; i++) {
        printf("    ");
    }

    // 노드 정체성에 따라 출력
    if (node->type == NODE_PIPE) {
        printf("┣━ [PIPE]\n");
    } 
    else if (node->type == NODE_CMD) {
        printf("┣━ [CMD] ");
        if (node->args != NULL) {
            for (int i = 0; node->args[i] != NULL; i++) {
                printf("'%s' ", node->args[i]);
            }
        }
        printf("\n");
    } 
    else if (node->type == NODE_REDIR) {
        printf("┣━ [REDIR] 타입: %d, 타겟: '%s'\n", node->redir_type, node->value);
    }

    // 왼쪽, 오른쪽 자식 노드로 계속 파고들기
    print_ast(node->left, depth + 1);
    print_ast(node->right, depth + 1);
}